travis:
  secure:
    BINSTAR_TOKEN: kVev1/2/15nCuesh95PnLcx3xAFqcjb+s2fGdgwZWnuje5NvWR++BV1qNPqFGlVqrtCuGL1WGyZglOi4egeU8Oit7Cj2Dj0ckbNqMK9eeVv8ae3tnyps4ft0+sjjd7QfR13pYy7yEjGNzHOYSrhWO2vD9G6wFOINxxAjV/3ToilHbuAkcM5eJiotoDo9PVs5nlQsl7NcUbfsp4jSZV+/055S0KWt2NnDx98UnhAiSLGaXNtsUw6DqUJIjbPJ2w2pQHLl+b27hvM7xslrCVQTpPmh3CTwLMXI7uZw191hquqrTP0I4vE8QrGzZ1ncOmZR4dtqTJ/Z3Dl398HM+NNW8bVpeSyF2kC5tF9r52tlrIrl79yzFyaIn27HCtX7XcmIgju8c6WY+mOYABipbvtgZISOPISJG3RR1Nyv55C6giMnuQmS3J+KAq/9EluK6Dbo4nQioNmgP64CRl+3o+xtiGA+8ciBQE+qvleJioFY3hm6mrA/K6EebJyTujR4k70NkIRI1refraKEKhgG3Jx5Uj8qsAU1vA+7TdtWdiOJsYZQxX3Lwpea9nv4ljt834rXPgTv2qVS+paQs+Cg9/lIIM3p4snVpE9dCvgoALwefE6LVW6IvYNrV7HqnNHGJkIdsCUtT8NPRlr4s7vd+ap0jzNSC/FfgJ7iGJbqRQyAKgc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
