travis:
  secure:
    BINSTAR_TOKEN: KN5tqCEdn9l2azg3OZ5FSG9pNkJK2Fj3HcNo+AniiiNczU7o/Rf51wsBNOgBU/DEhKMR842Gxohbr+Far3ZYYiCuYMXduutCEsBBV1DSAhY9aaNVhoPSIt2v40z5O4c1RLZgbT0wbEfLo5TCBbIwRHHK+UXiGYvT7rTyX/tGIZA/UYsDIJsp/8J7t6aGNCS7ZrtBM3D7skE/Mb8e3V/PqlWrDsUkF/Yy9ZMKuw4nWergvBryplDzOjIHKcbwz2R3UCpXgHZpJhGwjUboUmvhNqQPl/Xy7TsXgx8Mg9wCjdQSJN4agluyI3sfYIbJwkyxIoVbSS0eLtJit56P3HlP1PyBUAIk8YQRubbRGkqDIqO8qjdt52RAPXBGP91Qkdc5klKcPdBBfL4edvFYyn3BWBk7nXd8an5Fzt6G3zgtFuSBwXUYH1FKUodxVLXANrD2TcK98MnUoVVAf/IHFSvqJcstB28cWpMSBAIoCi6cT5fP5j+4JEHuIxFOYK+wuj/QMTLpfWz4z/Q4izZywlLzqQqCIu5KewW022iheISC6sOpuhgnyLHlUS0XBXQypL11zQXaPx+3hHW76Qz7Jz1juyowk4awlsDdVw0vbcCBSpgUSy8hzNx0jegHCCJ2dt9CvCqTrQGylLTM10edNvOZE9AuasbNikeV9Of65m0IB2I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
